In [66]:
from ffnn.healthcheck import healthcheck
healthcheck()

Healthcheck


In [67]:
from ffnn.ffnn import FFNN
from ffnn.types import ActivationFunction, LossFunction, WeightInitializer, WeightsSetup
import numpy as np

In [68]:
# 2 node di input layer, 3 node di hidden layer, 2 node di output layer
layer_sizes = [2, 2, 2]

activation_functions = [
    ActivationFunction.SIGMOID, 
    ActivationFunction.SIGMOID,
]

loss_function = LossFunction.MEAN_SQUARED_ERROR

weights_setup = [
    WeightsSetup(initializer=WeightInitializer.UNIFORM, lower_bound=0, upper_bound=1, seed=1),
    WeightsSetup(initializer=WeightInitializer.NORMAL, mean=0, variance=1, seed=1),
]

model = FFNN(
    layer_sizes=layer_sizes, 
    activation_functions=activation_functions, 
    loss_function=loss_function, 
    weights_setup=weights_setup,
    epochs=1,
    learning_rate=0.5,
    # random_state=42,
)

Layer initialized: 2 -> 2
Activation: ActivationFunction.SIGMOID
Weights setup: WeightsSetup(initializer=<WeightInitializer.UNIFORM: 2>, lower_bound=0, upper_bound=1, mean=None, variance=None, seed=817)
Weight initializer: WeightInitializer.UNIFORM

Layer initialized: 2 -> 2
Activation: ActivationFunction.SIGMOID
Weights setup: WeightsSetup(initializer=<WeightInitializer.NORMAL: 3>, lower_bound=None, upper_bound=None, mean=0, variance=1, seed=817)
Weight initializer: WeightInitializer.NORMAL

FFNN initialized
Layer sizes: [2, 2, 2]
Activation functions: [<ActivationFunction.SIGMOID: 3>, <ActivationFunction.SIGMOID: 3>]
Loss function: LossFunction.MEAN_SQUARED_ERROR
Weights setup: [WeightsSetup(initializer=<WeightInitializer.UNIFORM: 2>, lower_bound=0, upper_bound=1, mean=None, variance=None, seed=817), WeightsSetup(initializer=<WeightInitializer.NORMAL: 3>, lower_bound=None, upper_bound=None, mean=0, variance=1, seed=817)]
Learning rate: 0.5
Batch size: 32
Epochs: 1
Verbose: False
Rand

In [69]:
input_data = np.array([
    [0.05, 0.1],
])

target_data = np.array([
    [0.01, 0.99],
])

model.set_weights([
    np.array([
        [0.15, 0.25],
        [0.20, 0.30],
        [0.35, 0.35],
    ]),
    np.array([
        [0.40, 0.50],
        [0.45, 0.55],
        [0.60, 0.60],
    ]),
])

model.print_weights()

model.fit(input_data, target_data)

Layer 1 weights:
[[0.15 0.25]
 [0.2  0.3 ]
 [0.35 0.35]]

Layer 2 weights:
[[0.4  0.5 ]
 [0.45 0.55]
 [0.6  0.6 ]]

Epoch 1/1
Loss: 0.28047154558021875


In [70]:
model.print_weights()

Layer 1 weights:
[[0.14978134 0.24975114]
 [0.19956268 0.29950229]
 [0.34562681 0.34502287]]

Layer 2 weights:
[[0.35891648 0.51130127]
 [0.40866619 0.56137012]
 [0.53075072 0.61904912]]



In [71]:
model.predict(input_data)

array([[0.72844198, 0.77837719]])

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

In [ ]:
X, y = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)
X = X / 255.0
y = np.eye(10)[y.astype(int)]

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.7)
print(X_train.shape, X_test.shape)

(21000, 784) (49000, 784)


In [75]:
layer_sizes = [784, 40, 10]

activation_functions = [
    ActivationFunction.RELU,
    ActivationFunction.SIGMOID,
]

loss_function = LossFunction.MEAN_SQUARED_ERROR

weights_setup = [
    WeightsSetup(initializer=WeightInitializer.NORMAL, mean=0, variance=1, seed=1),
    WeightsSetup(initializer=WeightInitializer.NORMAL, mean=0, variance=1, seed=1),
]

model = FFNN(
    layer_sizes=layer_sizes, 
    activation_functions=activation_functions, 
    loss_function=loss_function, 
    weights_setup=weights_setup,
    epochs=100,
    random_state=42,
)

Layer initialized: 784 -> 40
Activation: ActivationFunction.RELU
Weights setup: WeightsSetup(initializer=<WeightInitializer.NORMAL: 3>, lower_bound=None, upper_bound=None, mean=0, variance=1, seed=42)
Weight initializer: WeightInitializer.NORMAL

Layer initialized: 40 -> 10
Activation: ActivationFunction.SIGMOID
Weights setup: WeightsSetup(initializer=<WeightInitializer.NORMAL: 3>, lower_bound=None, upper_bound=None, mean=0, variance=1, seed=42)
Weight initializer: WeightInitializer.NORMAL

FFNN initialized
Layer sizes: [784, 40, 10]
Activation functions: [<ActivationFunction.RELU: 2>, <ActivationFunction.SIGMOID: 3>]
Loss function: LossFunction.MEAN_SQUARED_ERROR
Weights setup: [WeightsSetup(initializer=<WeightInitializer.NORMAL: 3>, lower_bound=None, upper_bound=None, mean=0, variance=1, seed=42), WeightsSetup(initializer=<WeightInitializer.NORMAL: 3>, lower_bound=None, upper_bound=None, mean=0, variance=1, seed=42)]
Learning rate: 0.01
Batch size: 32
Epochs: 100
Verbose: False
Rando

In [76]:
print(y_train[:10])

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [77]:
model.fit(X_train, y_train)

Epoch 1/100
Loss: 0.5164141695956617
Epoch 2/100
Loss: 0.516326357318957
Epoch 3/100
Loss: 0.5162385960013808
Epoch 4/100
Loss: 0.5161508856032312
Epoch 5/100
Loss: 0.5160632314144232
Epoch 6/100
Loss: 0.5159756314759684
Epoch 7/100
Loss: 0.5158880843106771
Epoch 8/100
Loss: 0.5158005894322297
Epoch 9/100
Loss: 0.5157131469091494
Epoch 10/100
Loss: 0.5156257554293395
Epoch 11/100
Loss: 0.5155384138799506
Epoch 12/100
Loss: 0.5154511216721317
Epoch 13/100
Loss: 0.5153638805185818
Epoch 14/100
Loss: 0.5152766919545051
Epoch 15/100
Loss: 0.5151895415012269
Epoch 16/100
Loss: 0.5151024402890532
Epoch 17/100
Loss: 0.5150153881508617
Epoch 18/100
Loss: 0.51492838276421
Epoch 19/100
Loss: 0.5148414254265112
Epoch 20/100
Loss: 0.5147545129933523
Epoch 21/100
Loss: 0.5146676453410621
Epoch 22/100
Loss: 0.5145808240414997
Epoch 23/100
Loss: 0.5144940481060518
Epoch 24/100
Loss: 0.5144073178978122
Epoch 25/100
Loss: 0.5143206346826117
Epoch 26/100
Loss: 0.514233994256591
Epoch 27/100
Loss: 0.5141

In [78]:
model.print_weights()

Layer 1 weights:
[[ 0.49671415 -0.1382643   0.64768854 ... -1.95967012 -1.32818605
   0.19686124]
 [ 0.73846658  0.17136828 -0.11564828 ... -0.29900735  0.09176078
  -1.98756891]
 [-0.21967189  0.35711257  1.47789404 ... -1.16867804  1.14282281
   0.75193303]
 ...
 [-1.35563349 -0.03811314 -1.37162607 ...  0.88537699 -0.31350669
  -0.58011746]
 [-0.03929654 -1.34165212 -0.13858198 ... -0.63708118  0.45653317
   0.95364896]
 [-1.31395794 -0.20858697 -0.02477053 ...  0.9405914   0.90737436
   1.58001054]]

Layer 2 weights:
[[ 0.49669307 -0.13841212  0.64736071  1.52265317 -0.23444618 -0.23455915
   1.57883474  0.76712604 -0.47007999  0.54177346]
 [-0.46344871 -0.46625884  0.24157742 -1.91410156 -1.72599139 -0.56336697
  -1.01383182  0.31295839 -0.90968927 -1.41339691]
 [ 1.46549837 -0.22712007  0.06631941 -1.42609427 -0.54743336  0.1086933
  -1.15332197  0.37323507 -0.60376189 -0.29434546]
 [-0.60189124  1.8518962  -0.01766693 -1.06258314  0.81701544 -1.22650342
   0.20187139 -1.96385792

In [79]:
model.predict(X_test[:10])

array([[3.58826627e-36, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 9.98189768e-01, 1.00000000e+00, 2.23223595e-10,
        1.00000000e+00, 4.53986779e-26],
       [7.13019308e-23, 1.00000000e+00, 9.99999998e-01, 9.99956815e-01,
        1.00000000e+00, 9.99100876e-01, 1.71534743e-07, 1.65839865e-16,
        6.94406126e-01, 6.58146099e-13],
       [6.23827421e-25, 9.99999997e-01, 6.45365108e-34, 9.99996209e-01,
        2.48362332e-08, 4.39258996e-20, 1.00000000e+00, 9.99968772e-01,
        1.00000000e+00, 9.99995843e-01],
       [6.12614406e-13, 1.00000000e+00, 1.00000000e+00, 9.99999990e-01,
        9.99719875e-01, 8.84495859e-06, 1.05992301e-11, 7.27674001e-09,
        9.99999997e-01, 1.00000000e+00],
       [1.14750844e-30, 1.00000000e+00, 5.92321841e-01, 9.99999700e-01,
        1.00000000e+00, 9.99999996e-01, 1.00000000e+00, 3.90412933e-02,
        9.99999964e-01, 1.00000000e+00],
       [7.29112891e-25, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
   

In [80]:
y_pred = model.predict(X_test)
y_true = y_test

y_pred = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_true, axis=1)

accuracy = np.mean(y_pred == y_true)

print(accuracy)

0.0936530612244898
